DROP SEQUENCE IF EXISTS CREDIT_CARD_SEQ;
DROP TABLE IF EXISTS CREDIT_CARD;

CREATE SEQUENCE CREDIT_CARD_SEQ;
CREATE TABLE CREDIT_CARD(ID BIGINT default CREDIT_CARD_SEQ.nextval PRIMARY KEY, NAME VARCHAR(255), CARD_NUMBER BIGINT, BALANCE float4, MAX_LIMIT BIGINT);
