DROP SEQUENCE IF EXISTS CREDIT_CARD_SEQ ;
DROP TABLE IF EXISTS CREDIT_CARD;

CREATE SEQUENCE CREDIT_CARD_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE CREDIT_CARD(ID BIGINT default CREDIT_CARD_SEQ.nextval PRIMARY KEY, NAME VARCHAR(255), CARD_NUMBER BIGINT, BALANCE FLOAT8, MAX_LIMIT BIGINT);
